### ISSUE TITLE
Bluemix test antes de despliegue.

### ISSUE THREAD

**Issue by LuisGi93** [LuisGi93/IV16-17#1]
En bluemix para poder desplegar en github hay que utilizar hub.jazz.net y alli definir "trabajos" que se hagan antes del despliegue definiendo como último trabajo el despligue:
![2016-11-09-04-17-08_scrot](https://cloud.githubusercontent.com/assets/17405573/20132990/99e3ea80-a633-11e6-86ae-d8e92f1643d2.png)

Pero en hub.jazz.net no te dan ni virtualenv ni permisos para poder "instalar" la aplicación, realizar los test y posteriormente desplegarla.

**Comment by klyone** [comment]
@LuisGi93 Ok, le echo un ojo y te digo!

**Comment by klyone** [comment]
Buenas, he estado echando un ojo y no encuentro forma sencilla de hacerlo, salvo como te comenté en clase @LuisGi93 . Si veo algo más te aviso. ¿Has encontrado tú algo para solucionar este problema?

**Comment by LuisGi93** [comment]
Buenas, la verdad es que no tiene pinta de que haya una forma sencilla xD. Sigo igual que el último día, parece que soporta por ejemplo el uso de npm si tu proyecto es node y otras cosas parecidas para otros lenguajes como java pero para python con las herramientas que permiten en la fase de build no creo que haya forma.

**Comment by LuisGi93** [comment]
Buenas cierro y si en el futuro vuelvo a utilizar bluemix y encuentro la solución lo comento. Saludos.
