### ISSUE TITLE
Error http:500 tras despliegue en bluemix

### ISSUE THREAD

**Issue by LuisGi93** [LuisGi93/IV16-17#2]
![2016-11-09-04-24-20_scrot](https://cloud.githubusercontent.com/assets/17405573/20133192/7813a00c-a634-11e6-88ef-39c37ce66a3a.png)
A pesar de que localmente me funciona.

**Comment by LuisGi93** [comment]
Resulelto. Era un problema con el manifest.yml que al indicarle el host donde quería que se desplegara se pisaba con una url que previamente ya existia dando lugar a un resultado extraño.

**Comment by klyone** [comment]
@LuisGi93 Perfecto! Una cosa menos.
